[PRIMA-11882]: [Pyxis React] Aggiornare Spacing stories
primait/pyxis-react pull request #10
Opened 2021-11-24 15:17 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-11882

Story and test for Spacing

2021-11-24 15:28 UTC, emanuelemacri commented on src/stories/Spacing/Overview.tsx
> +        gridTemplateColumns="20%"
Qui non dovrebbe servire definire gridTemplateColumns (essendo tutti 1fr) o sbaglio?

2021-11-24 15:38 UTC, emanuelemacri requested changes

2021-11-24 15:38 UTC, emanuelemacri commented on src/stories/Spacing/Spacing.module.scss
> +    base: 5,
```suggestion
    base: 5px,
```

2021-11-24 15:38 UTC, emanuelemacri commented on src/stories/Spacing/Spacing.module.scss
> +}
Ok per ora, ma anche questa roba sparirà (essendo una duplicazione) una volta aggiunti i design token (mettiamo un todo anche qui)

2021-11-24 15:38 UTC, emanuelemacri commented on src/stories/Spacing/Spacing.module.scss
> +  .#{$size} {
Questo ci genera proprio delle classi che sono `xl`, `l`, ecc, mettiamo avanti un prefix tipo `space-`

2021-11-24 15:38 UTC, emanuelemacri commented on src/stories/Spacing/common.tsx
> +// TODO: to be replaced with design tokens
Scriviamo i todo sempre allo stesso modo? 👀 tipo `@todo` come nel file sopra

2021-11-24 16:33 UTC, lauratrapani commented on src/stories/Spacing/common.tsx
> +// TODO: to be replaced with design tokens
usata la versione `// TODO` come nelle altre storie anche nel scss

2021-11-25 08:26 UTC, emanuelemacri approved these changes
LGTM

2021-11-25 09:49 UTC, alessiosantangelo approved these changes

2021-11-25 09:50 UTC, merged