[PRIMA-12048]: [Pyxis Scss] Implementazione del componente Button
primait/pyxis-react pull request #13
Opened 2021-12-06 16:57 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-12048

Styling of button component.

2021-12-14 08:35 UTC, alessiosantangelo requested changes

2021-12-14 08:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +$_darkModeClass: lib.$darkModeClass;
Eliminiamo pure i riferimenti alla dark mode, non la svilupperemo nelle prime versioni di Pyxis. 

Nel caso lo facessimo useremmo [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) ma per evitare early abstraction possiamo non considerarla per ora.

2021-12-14 08:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +@mixin _filled ($gradient, $elevationColor) {
In questi mixins c'è un po' un mischione tra pseudoselettori, stati e modificatori dei bottoni.

Possiamo provare ad organizzare in maniera un po' più leggibile prevedendo un numero maggiore di `mixins/funzioni` private. 
Proverei quindi a strutturare come segue: 
```scss

@mixin _buttonShadow;

@mixin _buttonDisabled;

@mixin _buttonLoading;

@mixin _buttonIcon;

...
```

L'obiettivo è fare in modo che ogni mixin si occupi di un singolo stato/modificatore e si preoccupi di regolare il comportamento di un numero limitato di proprietà e stati così da rendere più facile la scrittura e il mantenimento del codice.

2021-12-14 08:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +    &.button--only-icon {
Sarebbe `button--icon-only` ma in ogni caso non mi è chiaro a cosa si riferisca. Se si tratta della semplice icona standalone dentro il bottone possiamo anche evitare di legare la sua classe all'elemento radice `button`.

In questo senso si può pensare di avere un semplice `.icon-button { ... }` così da non dover resettare certe regole.

2021-12-14 08:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +    }
Sfrutterei l'esempio di nomenclatura datoci da Google Material Design chiamando le icone:
- `leading-icon` al posto di prepend
- `trailing-icon` al posto di append

2021-12-14 08:35 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/lib/_variables.scss
> +/// @access public
Questo file può essere eliminato.

2021-12-14 09:13 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +$_darkModeClass: lib.$darkModeClass;
Abbiamo messo il riferimento alla dark mode perchè ci sono situazioni in cui il componente pensato per il tema dark potrebbe venire utilizzato anche nel tema light nel caso di sfondo scuro. Siccome anche lato design non c'è una divisione netta tra i due temi e per evitare il proliferare di varianti poco distinte tra di loro o poco chiare sulla situazione di utilizzo, abbiamo adottato questo metodo ibrido in cui basterebbe aggiungere una classe 'dark' al parent per cambiare il tema a tutti gli elementi contenuti.

2021-12-14 09:41 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +    &.button--only-icon {
```scss
@each $size, $properties in $_sizes {
  $dimension: lib.get($properties, dimension);
  $padding: lib.get($properties, padding);
  $iconSpacing: foundations.spacing(lib.get($properties, iconSpacing));

  .button--#{$size} {
    @include foundations.columnGap(lib.get($properties, columnGap));
    @include foundations.text(lib.get($properties, textSize), bold);
    height: $dimension;

    &:not(.button--ghost) {
      @include foundations.radius(lib.get($properties, radius));
      min-width: lib.get($properties, minWidth);
      padding: 0 foundations.spacing($padding);
    }

    &.button--trailing-icon {
      padding-right: $iconSpacing;
    }

    &.button--leading-icon {
      padding-left: $iconSpacing;
    }

    &.button--loading:after {
      height: lib.get($properties, loaderSize);
      width: lib.get($properties, loaderSize);
    }
  }

  &.icon-button--#{size}{
    width: $dimension;
    height: $dimension;

    &.button--loading:after {
      height: lib.get($properties, loaderSize);
      width: lib.get($properties, loaderSize);
    }
  }
}
```

Slegando la classe dalla principale il risultato non sarebbe comunque ottimale secondo me: se da un lato è vero che non ci sarebbero reset rispetto alla classe principale, dall'altro dovremmo portarci dietro alcune proprietà legate alla size del bottone che non possiamo semplicemente aggiungere con la classe relativa (che contiene anche le proprietà da resettare).

2021-12-14 09:48 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/buttons.scss
> +$_darkModeClass: lib.$darkModeClass;
https://github.com/primait/pyxis-react/pull/16#discussion_r768482772

2021-12-15 09:31 UTC, alessiosantangelo requested changes
L'implementazione mi pare ok ma credo vada lanciato il linter perchè ci sono delle parentesi senza lo spazio tra loro e il nome della regola. 

A proposito come mai il linter sta dicendo "tutto ok"?

2021-12-15 10:30 UTC, lauratrapani commented
Risposta a [questo commento](https://github.com/primait/pyxis-react/pull/13#pullrequestreview-832546229).

Mancava l'impostazione del linter ed è stato aggiunto.

La scelta per il nome è dovuta al fatto che `dark` non si riferisce ad una proprietà del bottone ma dello sfondo. Il bottone invece è bianco, per questo la versione è `light`. La proposta `alt` invece secondo me è poco parlante, mentre `on-dark-bg` si riferirebbe all'uso del bottone e non ad una sua proprietà.

2021-12-15 15:56 UTC, alessiosantangelo approved these changes

2021-12-15 15:56 UTC, merged