[PRIMA-11997]: [Pyxis] Implementazione delle icone
primait/pyxis-react pull request #14
Opened 2021-12-09 13:33 UTC by lauratrapani

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-11997

Style and react component for icon.

2021-12-13 11:03 UTC, Gsciarra commented
Il file `Icon.elm` è privo di documentazione. Preferirei fare una card a parte dedicata solo a quello.

2021-12-13 12:11 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +configToHtmlAttributes config =
Scritto in questo modo ho il timore che all'aumentare degli attributi diventi un' esplosione di codice poco leggibile, misto di (::) e (++) infissi di cui diventa un po' difficile capire la semantica e l'ordine a colpo d'occhio

Per esempio (è giusto un suggerimento, vedete voi se è abbastanza generico/utile) un modo di riorganizzare potrebbe essere una cosa del tipo:
```elm
addStroke : Maybe String -> List (Html.Attribute msg)
addStroke mStroke =
    case mStroke of
        Nothing ->
            []

        Just stroke ->
            [ Html.Attributes.attribute "stroke" stroke ]


addDescription : Maybe String -> List (Html.Attribute msg)
addDescription mDesc =
    case mDesc of
        Nothing ->
            []

        Just desc ->
            [ Html.Attributes.attribute "role" "img"
            , Html.Attributes.attribute "description" desc
            ]

makeAttributes : Config msg -> List (Html.Attribute Never)
makeAttributes config =
    List.concat
        -- Qui tutti gli attributi condizionali
        [ addDescription config.description
        , addStroke config.stroke

        -- Qui tutti gli attributi non condizionali
        , [ sizeToAttribute config.size
          , variantToAttribute config.variant
          ]
        ]
```

Questo boilerplate si può eliminare ulteriormente con una utility (riusabile) del tipo:
```elm
makeAttrs : (a -> List (Html.Attribute msg)) -> Maybe a -> List (Html.Attribute msg)
makeAttrs f m =
    case m of
        Nothing ->
            []

        Just x ->
            f x


addStroke : Maybe String -> List (Html.Attribute msg)
addStroke =
    makeAttrs <| \stroke -> [ Html.Attributes.attribute "stroke" stroke ]


addDescription : Maybe String -> List (Html.Attribute msg)
addDescription =
    makeAttrs <|
        \desc ->
            [ Html.Attributes.attribute "role" "img"
            , Html.Attributes.attribute "description" desc
            ]
            
-- Il resto è invariato
```

2021-12-13 12:11 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +module Icon exposing (Size, accessKey, class, isBoxed, large, medium, size, small, view)
(Questa è più una curiosità) come mai viene esposto class? Non rompe un po' il design system?

2021-12-13 12:11 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +    Html.div
(la butto lì, non so nemmeno se abbia senso) altre librerie usano il tag `<i>` per wrappare le icone.
`i` in realtà sta per `italic`, quindi dal punto di vista semantico non serve, credo sia solo mnemonico per `icon`. Però magari, non avendo degli elm component devtools, può essere più comodo visivamente avere un `<i>` anziché uno dei mille `<div>`  quando si usa i devtools del browser?

2021-12-13 14:07 UTC, Gsciarra commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +isBoxed =
`large` è un valore da passare a `size`, mentre `isBoxed` è un flag come potrebbe esserlo un `autofocus` sull'html.

2021-12-13 14:15 UTC, Gsciarra commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +    Html.div
[Tag i](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i?retiredLocale=it) sarebbe un uso improprio.

2021-12-13 14:17 UTC, Gsciarra commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +module Icon exposing (Size, accessKey, class, isBoxed, large, medium, size, small, view)
Anche se non dovrebbe succedere, chiunque ha il potere di modificare lo stile degli elementi in maniera impropria se lo vuole. Togliere la possibilità di passare una classe, complicherebbe solo la vita a chi vorrebbe solo dare un margin e porterebbe noi a dover gestire una grande mole di parametri per poter gestire e controllare tutti i casi.

2021-12-13 14:29 UTC, Gsciarra commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +configToHtmlAttributes config =
La modifica che suggerisci è per gli Html.Attribute che difficilmente cresceranno, perché se non abbiamo la necessità di assicurarci che non siano duplicati, li passiamo direttamente a config.attributes, senza dover gestire altro.

2021-12-13 15:17 UTC, kioan000 requested changes
Ho fatto solo la review della parte di elm. Aspetto lo split per guardarla meglio.
Sono abbastanza contrario al ripensare le API in questo modo, è una strada che avevamo già battuto (avevo fatto una proposta molto simile, credo ci sia ancora la proposal qua su GitHub da qualche parte) ma l'avevamo cassata per molti motivi.
edit
eccola [qua](https://github.com/primait/pyxis-components/issues/28)

2021-12-13 18:01 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +    = Size String
Intendi esporre direttamente `withSizeLarge : Icon.Attribute` , ecc?
Modellare `Size` come tipo (comunque opaco, altrimenti sarebbero breaking changes) significa poterlo passare in giro.
Ad esempio se il bottone oggi si usa così
```elm
Btn.view [ Btn.icon Icon.loading  ] "Click me"
```

Avere un tipo size permette (eventualmente, un domani) di fare
```elm
Btn.view [ Btn.icon Icon.loading, Btn.iconSize Icon.large  ] "Click me"
```

L'alternativa sarebbe dover necessariamente prendere un argomento del tipo
```elm
Btn.view [ Btn.icon Icon.loading, Btn.iconAttributes [ Icon.sizeLarge ]  ] "Click me"
```
ma potrebbe darsi che l'autore del component ritenga sbagliato, in quel contesto, dare libertà arbitraria su ogni attributo del bottone.
Quindi in generale modellerei il modellabile (variants, sizes, colors, ecc) come tipi (opachi), perchè è un caso d'uso parecchio comune

2021-12-13 18:53 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +view : List Attribute -> Icon -> Html msg
Vedo (dal link nel commento prima) che effettivamente vari anni fa avevate già previsto questo stile per l'API, e scartata a favore del builder pattern, come mai? Dal codice che ho visto fin'ora in giro, mi sembra che, a posteriori, quello stile presenti gravi problemi di leggibilità, e ora che tanto comunque si tratta di fare breaking changes, mi sembra l'occasione per fare delle potenziali migliorie.

Immagino che ci saranno dei documenti (o vecchi thread) che spiegano le decisioni prese, quindi nel caso se hai qualcosa da linkare leggo con interesse, però comunque chiedo:

> Dovrebbe chiamarsi render

In elm è idiomatico il verbo `view` per questo tipo di funzione, come mai render? Non è strano se poi i moduli espongono funzioni del tipo:
```elm
type Model
init : Model
type : Msg
update : Msg -> Model -> Model
render : Model -> Html Msg -- Eh?
```
a meno che non si voglia usare con alcuni components il verbo `view` e con altri `render`

> i modifier **devono** cominciare tutti con with in modo da distinguerli dai costruttori

i costruttori avrebbero un tipo (e una sezione nella documentazione) diversa rispetto agli attributes. Siamo sicuri che creerebbero confusione? Perché se l'intento è chiaramente quello di imitare il DSL dell'html di elm, mi sembra un po' strano che ci sia
```elm
div [ class "something" ] [ ]
```

ma

```elm
Btn.view [ withClass "something" ] [ ]
```

> Un banale withClass può già modificare la lista degli attribute

Qui non sono sicuro di aver capito cosa intendi, ma se intendi di fare (per esempio) che `withSize` internamente usi withClass, farlo così serve a fare in modo che ce ne sia una e una sola

> Comprendo il tentativo di cercare di separare "parti custom" e "parti obbligatorie" [...]

Lo snippet che hai segnato direi che semplicemente non esisterebbe, secondo questo stile di API. Sarebbe semplicemente

```elm
Component.view 
        [ Component.classAttribute "xx"
        , Component.clickAttribute MyMsg 
        , Component.withInnerClass "ccc"
        ]
```
In generale:
```ts
-- Component con soli attributi opzionali
Comp.view [ att1, ... attn ]

-- Component con soli attributi opzionali e "children-like" (es. options di select, label di btn, ecc)
Comp.view [ att1, ... attn ] [child1, ... childn]
-- Altrimenti, figata la "scoped slots"-style API nella vecchia proposal che avevi fatto, non ci avevo pensato

-- Component con soli attributi opzionali e "children-like" singolo (es. string)
Comp.view [ att1, ... attn ] "text"

-- Component con attributi opzionali e obbligatori e "children-like"
Comp.view { x = vx, y = vy } [ att1, ... attn ] [child1, ... childn]

-- A volte degli argomenti obbligatori possono essere impliciti nel costruttore
-- Es. il Btn che deve avere sempre una variant
Btn.primary [att1, ...attn]
```

Quindi in generale non vedo situazioni di cattiva leggibilità, mi sfugge qualcosa? Perché ci dovrebbero essere dei modificatori "dentro"? Così come in React si passano sempre gli attributi (props) in un punto solo, perché qua non dovrebbe bastare? Quali sono degli esempi di caso d'uso concreti in cui uscirebbe fuori un caso del genere?

2021-12-13 18:58 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +        |> Html.map never
Diciamo che in effetti la scelta "safe" è renderlo `Attribute msg` perché così non farebbe breaking changes eventualmente. Però hai per caso a portata di mano del codice in cui serviva dare degli eventi proprio alle icone (e non al parent, che magari è proprio un `button` o simili)? Giusto per capire il caso d'uso (e se in effetti non sia proprio il parent che debba ascolare l'evento)

2021-12-14 12:09 UTC, eFFeeMMe commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +type Attribute
onClick ok ma magari onHover? Oppure drag'n'drop oppure css transition... Non saprei se non ci servirà *mai* :eyes:

2021-12-14 13:06 UTC, ascandone commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +type Attribute
Mh in effetti l'evento `animationend` come funziona? Non funziona sul parent vero?

2021-12-14 13:57 UTC, eFFeeMMe commented on packages/pyxis-elm/scripts/elm-svg-generator/src/Icon.example.elm
> +view : List Attribute -> Icon -> Html msg
Ammetto che anche a me piacerebbe come API qualcosa che rassomigliasse ad `Html` di Elm invece che il builder pattern... Le discussioni sulla forma delle API di Pyxis v3 sono state fatte un bel po' di tempo fa (non c'ero ancora neanch'io :grimacing: ) ed alla luce delle esperienze di Pyxis v2, mentre magari ora con l'esperienza di Pyxis v3 qualcosa può essere cambiato?

2021-12-16 14:33 UTC, closed without merging