[PRIMA-11997]: [Pyxis] Implementazione delle icone
primait/pyxis-react pull request #16
Opened 2021-12-13 15:00 UTC by Gsciarra

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-11997

Icon implementation in pyxis-scss from https://github.com/primait/pyxis-react/pull/14

2021-12-14 08:38 UTC, alessiosantangelo requested changes

2021-12-14 08:38 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/icons.scss
> +  .#{lib.$darkModeClass} & {
La dark mode non verrà supportata nelle prime versioni di Pyxis (e forse neanche in futuro). Nel caso comunque lo faremmo via _prefers-color-scheme_.

2021-12-14 08:38 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/lib/_variables.scss
> +$darkModeClass: "dark";
Si può eliminare.

2021-12-14 09:14 UTC, lauratrapani commented on packages/pyxis-scss/src/scss/components/icons.scss
> +  .#{lib.$darkModeClass} & {
Come scritto nell'altra pr, abbiamo messo il riferimento alla dark mode perchè ci sono situazioni in cui il componente pensato per il tema dark potrebbe venire utilizzato anche nel tema light nel caso di sfondo scuro. Siccome anche lato design non c'è una divisione netta tra i due temi e per evitare il proliferare di varianti poco distinte tra di loro o poco chiare sulla situazione di utilizzo, abbiamo adottato questo metodo ibrido in cui basterebbe aggiungere una classe 'dark' al parent per cambiare il tema a tutti gli elementi contenuti.

2021-12-14 09:48 UTC, alessiosantangelo commented on packages/pyxis-scss/src/scss/components/icons.scss
> +  .#{lib.$darkModeClass} & {
> abbiamo messo il riferimento alla dark mode perchè ci sono situazioni in cui il componente pensato per il tema dark potrebbe venire utilizzato anche nel tema light nel caso di sfondo scuro.

Non sono convinto. Il fatto che il componente si possa utilizzare su sfondo scuro non significa che sia un componente del tema dark. 
Anzi, in questo caso significa proprio che è parte della skin di default di Pyxis e che la regola di utilizzo è definita dal mockup e non dalla scelta dello schema colori dell'utente.

2021-12-15 17:42 UTC, Gsciarra commented
@alessiosantangelo potresti ridare un occhio?

2021-12-16 09:48 UTC, alessiosantangelo approved these changes

2021-12-16 09:51 UTC, merged